# Generated by Django 3.1 on 2022-03-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_of_build',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='economic_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کد اقتصادی'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fuel_store_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد فروشندگی های سوخت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='last_fund_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد سهام و آخرین سرمایه ثبتی'),
        ),
        migrations.AlterField(
            model_name='company',
            name='member_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد اعضاء'),
        ),
        migrations.AlterField(
            model_name='company',
            name='national_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره شناسه ملی'),
        ),
        migrations.AlterField(
            model_name='company',
            name='oil_position_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد جایگاه مواد نفتی'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='register_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='شماره ثبت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'فعال'), (1, 'غیرفعال')], null=True, verbose_name='وضعیت شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='village_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد روستاهای حوزه عمل'),
        ),
    ]
