# Generated by Django 3.1 on 2022-03-02 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_auto_20220302_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='companyMember',
        ),
        migrations.AddField(
            model_name='companymember',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.company', verbose_name='شرکت'),
        ),
    ]
