# Generated by Django 3.1 on 2022-03-02 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_auto_20220302_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagegroup',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'اخبار'), (1, 'اطلاعیه ها'), (2, 'مطالب روزانه'), (2, 'آموزشی'), (3, 'درباره ما'), (4, 'تماس با ما'), (5, 'سایر')], verbose_name='نوع'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام نام خانوادگی')),
                ('description', models.CharField(max_length=500)),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره همراه')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='آدرس الکترونیکی')),
                ('job', models.CharField(blank=True, max_length=150, null=True, verbose_name='شغل')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'فعال'), (1, 'غیرفعال')], verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ویرایش')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.page')),
            ],
        ),
    ]
