# Generated by Django 3.1 on 2022-03-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_auto_20220302_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'دسته بندی'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'دیدگاه'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'شرکت ها'},
        ),
        migrations.AlterModelOptions(
            name='companymember',
            options={'verbose_name_plural': 'اعضاء'},
        ),
        migrations.AlterModelOptions(
            name='externallink',
            options={'verbose_name_plural': 'لینک خارجی'},
        ),
        migrations.AlterModelOptions(
            name='navbar',
            options={'verbose_name_plural': 'منو'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': 'صفحه'},
        ),
        migrations.AlterModelOptions(
            name='pagegroup',
            options={'verbose_name_plural': 'گروه بندی صفحه'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'خدمات'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'اسلایدر'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'برچسب'},
        ),
    ]
