# Generated by Django 3.1 on 2022-03-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_auto_20220302_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('icon', models.CharField(max_length=100, verbose_name='آیکن')),
                ('link', models.URLField(verbose_name='لینک')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.AddField(
            model_name='navbar',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آیکن'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آیکن'),
        ),
    ]
