# Generated by Django 3.1 on 2022-03-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_auto_20220303_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagegroup',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'اخبار'), (1, 'اطلاعیه ها'), (2, 'مطالب آموزشی'), (4, 'درباره ما'), (5, 'تماس با ما'), (6, 'سایر')], verbose_name='نوع'),
        ),
    ]
