# Generated by Django 3.1 on 2022-03-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_auto_20220227_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=350, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
